package vistas;

import javax.swing.JDialog;
import simulacion.ResultadosData;



public class Resultados extends javax.swing.JFrame {
    int tiempoSimulacion = 0;
    MostrarTablaEventos eventos;
    ResultadosData data;
    EstadisticasServidor stats;
    
    public Resultados(int tiempoSimulacion, MostrarTablaEventos eventos, ResultadosData data, EstadisticasServidor stats) {
              
        this.tiempoSimulacion = tiempoSimulacion;
        this.eventos = eventos;
        this.stats = stats;
        initComponents();
        this.setLocationRelativeTo(null);
        this.parametrosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Clientes que no esperan", data.getClientesNoEsperanCount()},
                {"Cantidad de clientes que se van sin ser atendidos ", data.getClientesNoAtendidosCount()},
                {"Probabilidad de esperar", data.getProbabilidadEspera()},
                {"Cantidad promedio de clientes en cola", data.getClientesPromedioCola()},
                {"Cantidad promedio de clientes en Sistema", data.getClientesPromedioSistema()},
                {"Tiempo promedio de un cliente en cola", data.getTiempoPromedioCola()},
                {"Tiempo promedio de un cliente en Sistema", data.getTiempoPromedioSistema()},
                {"Tiempo promedio de espera del cliente que hace cola ", data.getTiempoPromedioEspera()},
                {"Tiempo promedio adicional que se trabaja después de cerrar", null},
                {"Porcentaje de utilización general de servidores", data.getPorcentajeUtilGeneral()},
                {"Relación óptima de costos: servidores y espera de cliente ", null},
            },
            new String [] {
                "Parametro", "Resultado"
            }
        ));
        
         this.parametrosTablaBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Total clientes en banco", data.getContCliente()},
                {"Tiempo medio que pasa un cliente en el banco hasta ser atendido", data.getTiempoPromedioCola()},
                {"Probabilidad de que un cliente espere mas de cinco minutos", data.getProbabilidadEsperaCincoMinutos()},
                {"Tiempo promedio que estan ociosos los empleados", data.getTiempoOciosoServidores()},
            },
            new String [] {
                "Parametro", "Resultado"
            }
        ));
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        verTablaBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        parametrosTabla = new javax.swing.JTable();
        aceptarBoton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        parametrosTablaBanco = new javax.swing.JTable();
        showStats = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resultados");

        verTablaBoton.setText("Ver tabla de eventos");
        verTablaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTablaBotonActionPerformed(evt);
            }
        });

        parametrosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Clientes que no esperan", null},
                {"Cantidad de clientes que se van sin ser atendidos ", null},
                {"Probabilidad de esperar", null},
                {"Cantidad promedio de clientes en cola", null},
                {"Cantidad promedio de clientes en Sistema", null},
                {"Tiempo promedio de un cliente en cola", null},
                {"Tiempo promedio de un cliente en Sistema", null},
                {"Tiempo promedio de espera del cliente que hace cola ", null},
                {"Tiempo promedio adicional que se trabaja después de cerrar", null},
                {"Porcentaje de utilización de cada servidor y general", null},
                {"Relación óptima de costos: servidores y espera de cliente ", null}
            },
            new String [] {
                "Parametro", "Resultado"
            }
        ));
        parametrosTabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(parametrosTabla);
        if (parametrosTabla.getColumnModel().getColumnCount() > 0) {
            parametrosTabla.getColumnModel().getColumn(1).setResizable(false);
        }

        aceptarBoton.setText("Aceptar");
        aceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBotonActionPerformed(evt);
            }
        });

        parametrosTablaBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Total clientes en banco", null},
                {"Tiempo medio que pasa un cliente en el banco hasta ser atendido", null},
                {"Probabilidad de que un cliente espere mas de cinco minutos", null},
                {"Tiempo promedio que estan osciosos los empleados", null}
            },
            new String [] {
                "Parametro", "Resultado"
            }
        ));
        parametrosTablaBanco.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(parametrosTablaBanco);
        if (parametrosTablaBanco.getColumnModel().getColumnCount() > 0) {
            parametrosTablaBanco.getColumnModel().getColumn(1).setResizable(false);
        }

        showStats.setText("Ver estadisticas de servidores");
        showStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verTablaBoton)
                        .addGap(49, 49, 49)
                        .addComponent(showStats)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aceptarBoton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showStats)
                    .addComponent(verTablaBoton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aceptarBoton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void initResults(){};
    
    private void verTablaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTablaBotonActionPerformed
        eventos.setVisible(true);
    }//GEN-LAST:event_verTablaBotonActionPerformed

    private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBotonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_aceptarBotonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void showStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStatsActionPerformed
        // TODO add your handling code here:
       this.stats.setVisible(true);
    }//GEN-LAST:event_showStatsActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton aceptarBoton;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable parametrosTabla;
    public javax.swing.JTable parametrosTablaBanco;
    public javax.swing.JButton showStats;
    public javax.swing.JButton verTablaBoton;
    // End of variables declaration//GEN-END:variables
}
